Handle un-formatting nodes
matrix-org/matrix-wysiwyg pull request #87
Opened 2022-09-13 16:10 UTC by aringenbach

Allow to un-format selected nodes

![Simulator Screen Recording - iPhone 13 - 2022-09-13 at 17 46 18](https://user-images.githubusercontent.com/80891108/189952328-f68a196e-1346-42ab-8808-e46081430d5b.gif)

2022-09-14 08:22 UTC, andybalaam reviewed
Looks good so far.

2022-09-14 08:22 UTC, andybalaam commented on crates/wysiwyg/src/composer_model/format.rs
> +                        if f.clone() == format.clone() {
Should be able to do if `f == format` without cloning, or something similar.

2022-09-14 08:22 UTC, andybalaam commented on crates/wysiwyg/src/dom/nodes/container_node.rs
> +    pub fn remove_child_and_own_hierarchy(
Can we find a better name e.g. `remove_child_and_take_grandchildren` ? (Or something better??)

2022-09-15 07:20 UTC, jmartinesp commented on crates/wysiwyg/src/composer_model/format.rs
> +                        if f.clone() == format.clone() {
This seems to work fine:

```suggestion
                        if *f == format {
```

2022-09-15 07:22 UTC, jmartinesp commented on crates/wysiwyg/src/composer_model/format.rs
> +                    if f.clone() == format {
Same here, `*f` is probably enough to use the reference's contents.

```suggestion
                    if *f == format {
```

2022-09-15 07:30 UTC, jmartinesp commented
I'm actually surprised at how little code it took to write `unformat_several_nodes` by just removing the formatting node altogether and then re-creating it. I spent several days in this banging my head before giving up and this solution is *so simple*. Congrats!

2022-09-15 14:49 UTC, aringenbach commented on crates/wysiwyg/src/dom/dom_struct.rs
> +                        parent.insert_child(index, child.clone());
I really wish we could avoid this clone, otherwise it is not really better than cloning the entire children array and using existing `replace` fn

2022-09-15 15:09 UTC, jmartinesp approved these changes
LGTM! It also seems to work great on Android.

2022-09-16 08:11 UTC, andybalaam requested changes
Just more tests please!

2022-09-16 08:11 UTC, andybalaam commented on crates/wysiwyg/src/composer_model/format.rs
> +    #[test]
I'd like to see a lot more tests in `test_formatting.rs` - then this looks good to go!

2022-09-16 10:28 UTC, aringenbach commented on crates/wysiwyg/src/tests/test_formatting.rs
> +#[ignore] // TODO: partial_unformat_toplevel_node_reconstructs_expected_model
pretty sure this is fixed by removing SameNode

2022-09-16 10:32 UTC, andybalaam approved these changes
Looks great!

2022-09-16 10:35 UTC, merged